import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { ToDoList } from "../presentation/ToDoList";

function Home(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>CLEAN Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CLEAN <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <ToDoList />
      </main>
    </div>
  );
}

export default Home;
