import Head from "next/head";
import { Container } from "../Container";

interface Props {
  children: JSX.Element | JSX.Element[];
  title: string;
}

export function Page({ children, title }: Props): JSX.Element {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>{children}</Container>
    </div>
  );
}
